# Generated by Django 2.2.12 on 2020-12-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('actions_allowed', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'user_role_actions',
            },
        ),
    ]
