# Generated by Django 2.2.12 on 2020-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201229_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDataSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=30, null=True)),
                ('related', models.CharField(max_length=100, null=True)),
                ('record_count', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'app_data_sets',
            },
        ),
        migrations.CreateModel(
            name='ItemCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=30, null=True)),
                ('count_type', models.CharField(max_length=100, null=True)),
                ('plan_total', models.CharField(max_length=100, null=True)),
                ('plan_rows', models.CharField(max_length=30, null=True)),
                ('plan_year', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'item_counts',
            },
        ),
        migrations.CreateModel(
            name='ItemReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=30, null=True)),
                ('reference_type', models.CharField(max_length=100, null=True)),
                ('reference_value', models.CharField(max_length=100, null=True)),
                ('reference_source', models.CharField(max_length=30, null=True)),
                ('info', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'item_references',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=30, null=True)),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('long_description', models.CharField(max_length=100, null=True)),
                ('item_type', models.CharField(max_length=30, null=True)),
                ('last_used', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=100, null=True)),
                ('location_name', models.CharField(max_length=30, null=True)),
                ('info', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=30, null=True)),
                ('item_id', models.CharField(max_length=100, null=True)),
                ('tran_date', models.CharField(max_length=100, null=True)),
                ('trans_user', models.CharField(max_length=30, null=True)),
                ('trans_type', models.CharField(max_length=100, null=True)),
                ('entity', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=30, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('warehouse', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('bin', models.CharField(max_length=100, null=True)),
                ('revenue', models.CharField(max_length=30, null=True)),
                ('cost', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'item_trans',
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=30, null=True)),
                ('container_pod', models.CharField(max_length=100, null=True)),
                ('help_text', models.CharField(max_length=100, null=True)),
                ('last_used', models.CharField(max_length=30, null=True)),
                ('usage_count', models.CharField(max_length=100, null=True)),
                ('roles_used', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=30, null=True)),
                ('container_pod', models.CharField(max_length=100, null=True)),
                ('help_text', models.CharField(max_length=100, null=True)),
                ('last_used', models.CharField(max_length=30, null=True)),
                ('usage_count', models.CharField(max_length=100, null=True)),
                ('roles_used', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'role_menu',
            },
        ),
    ]
