# Generated by Django 2.2.12 on 2020-12-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appdatasets_itemcounts_itemreferences_items_itemtrans_menuitems_rolemenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolemenu',
            old_name='container_pod',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='rolemenu',
            old_name='last_used',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='rolemenu',
            old_name='description',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='rolemenu',
            old_name='help_text',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='roles_used',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='rolemenu',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='menu_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
