# Generated by Django 2.2.12 on 2020-12-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201230_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rolemenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
