# Generated by Django 2.2.12 on 2020-12-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201230_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtrans',
            name='revenue_fld',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
