# Generated by Django 2.2.12 on 2020-12-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201230_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtrans',
            old_name='revenue',
            new_name='abcd1',
        ),
    ]
