# Generated by Django 2.2.12 on 2020-12-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201230_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtrans',
            old_name='abcd1',
            new_name='revenue',
        ),
    ]
