# Generated by Django 2.2.12 on 2020-12-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201230_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTrans',
        ),
    ]
