# Generated by Django 2.2.12 on 2020-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_itemtrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=30, null=True)),
                ('item_id', models.CharField(max_length=100, null=True)),
                ('tran_date', models.CharField(max_length=100, null=True)),
                ('trans_user', models.CharField(max_length=30, null=True)),
                ('trans_type', models.CharField(max_length=100, null=True)),
                ('entity', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=30, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('warehouse', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('bin', models.CharField(max_length=100, null=True)),
                ('revenue', models.CharField(max_length=100, null=True)),
                ('cost', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'item_trans',
            },
        ),
    ]
