# Generated by Django 2.2.12 on 2020-12-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_itemtrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtrans',
            name='revenue11',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
