# Generated by Django 2.2.12 on 2020-12-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_itemtrans_revenue11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtrans',
            name='revenue',
        ),
    ]
