# Generated by Django 2.2.12 on 2020-12-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_itemtrans_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTrans',
        ),
    ]
