ACCOUNT_NOT_VERIFIED = 'Your account is not verified yet.'
ACCOUNT_NOT_FOUND = 'register'
EMAIL_NOT_VERIFIED = 'email'
PHONE_NOT_VERIFIED = 'phone'
EMAIL_VERIFIED_SUCCEED = 'Thank you for your email confirmation. Now you can login to your account.'
EMAIL_VERIFIED_LINK_INVALID = 'Email verification link is invalid!'
